{% set name = "unifuncnet" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PedroMTQ/UniFuncNet/archive/refs/tags/{{ version }}.tar.gz
  sha256: a81b74e63db64a9ecb6bbc97d4e26e274ad250f1d5a5ebaa3f7643db5006d870

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - unifuncnet=unifuncnet.__main__:main

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=42
    - wheel
  run:
    - beautifulsoup4
    - lxml
    - python >=3.9
    - requests

test:
  imports:
    - unifuncnet
  commands:
    - pip check
    - unifuncnet --help
  requires:
    - pip

about:
  home: https://github.com/PedroMTQ/UniFuncNet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Biological network annotation tool.
  description: |
    UniFuncNet is network annotation tool that integrates multiple biological 
    databases into one composite output.
  dev_url: https://github.com/PedroMTQ/UniFuncNet

extra:
  recipe-maintainers:
    - PedroMTQ
